### PR TITLE
Support pktmon sniffing

### PR DESCRIPTION
**Pull request by Blondy314**
Adding support for capturing packets with pktmon (Packet Monitor) and dissecting packets

### CODE REVIEW

**Comment by citronneur** [comment]
Thanks for contribution, I will work on it as soon as possible

**Comment by Blondy314** [comment]
Thanks :)Inbar.
-------- Original message --------From: Sylvain Peyrefitte ***@***.***> Date: 12/1/21  11:42  (GMT+02:00) To: airbus-cert/Winshark ***@***.***> Cc: Blondy314 ***@***.***>, Author ***@***.***> Subject: Re: [airbus-cert/Winshark] Support pktmon sniffing (PR #3) 
Thanks for contribution, I will work on it as soon as possible

**Comment by Blondy314** [comment]
Any update on this?

**Comment by eladsolomon-ms** [comment]
+1 waiting for this as well

**Comment by Blondy314** [comment]
Hi,

Pinging on this again.
I Would be happy to see it in the main branch so people can use it (I have
been asked about this a few times and referred people to my side branch).

Thanks,
Inbar.

**Comment by Blondy314** [comment]
Thanks.

Perhaps it will also be good to create a new release.

**Pull request merged**
